-- MySQL Script generated by MySQL Workbench
-- ср, 11-лип-2018 17:46:56 +0300
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`readers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`readers` (
  `id` INT NULL AUTO_INCREMENT COMMENT 'генератор',
  `lastname` VARCHAR(255) NULL COMMENT 'фамилия',
  `firstname` VARCHAR(255) NULL COMMENT 'имя',
  `created_id` DATETIME NULL COMMENT 'дата создания',
  `modified_id` DATETIME NULL COMMENT 'дата модификации',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Читатели';


-- -----------------------------------------------------
-- Table `mydb`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`books` (
  `id` INT NULL AUTO_INCREMENT COMMENT 'генератор',
  `name` VARCHAR(255) NULL COMMENT 'наименование',
  `description` VARCHAR(255) NULL COMMENT 'краткое описание',
  `num_pages` SMALLINT(2) NULL COMMENT 'количество страниц',
  `published` CHAR(4) NULL COMMENT 'дата публикации',
  `created_id` DATETIME NULL COMMENT 'дата создания',
  `modified_id` DATETIME NULL COMMENT 'дата модификации',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Комментарии читателей к книгам';


-- -----------------------------------------------------
-- Table `mydb`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comments` (
  `id` INT NULL AUTO_INCREMENT COMMENT 'генератор',
  `readers_id` INT NOT NULL COMMENT 'код читателя',
  `books_id` INT NOT NULL COMMENT 'код книги',
  `created_id` DATETIME NULL COMMENT 'дата создания',
  `modified_id` DATETIME NULL COMMENT 'дата модификации',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Comments_Readers1_idx` (`readers_id` ASC),
  INDEX `fk_Comments_Books1_idx` (`books_id` ASC),
  CONSTRAINT `fk_Comments_Readers1`
    FOREIGN KEY (`readers_id`)
    REFERENCES `mydb`.`readers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comments_Books1`
    FOREIGN KEY (`books_id`)
    REFERENCES `mydb`.`books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Комментарии читателей к книгам';


-- -----------------------------------------------------
-- Table `mydb`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`authors` (
  `id` INT NULL AUTO_INCREMENT COMMENT 'генератор',
  `lastname` VARCHAR(255) NULL COMMENT 'фамилия',
  `firstname` VARCHAR(255) NULL COMMENT 'имя',
  `created_id` DATETIME NULL COMMENT 'дата создания',
  `modified_id` DATETIME NULL COMMENT 'дата модификации',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Авторы';


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `id` INT NULL AUTO_INCREMENT COMMENT 'генератор',
  `name` VARCHAR(255) NULL COMMENT 'наименование',
  `created_id` DATETIME NULL COMMENT 'дата создания',
  `modified_id` DATETIME NULL COMMENT 'дата модификации',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Категории книг';


-- -----------------------------------------------------
-- Table `mydb`.`subs_readers_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subs_readers_category` (
  `id` INT NULL AUTO_INCREMENT COMMENT 'генератор',
  `category_id` INT NOT NULL COMMENT 'код категории',
  `readers_id` INT NOT NULL COMMENT 'код читателя',
  `created_id` DATETIME NULL COMMENT 'дата создания',
  `modified_id` DATETIME NULL COMMENT 'дата модификации',
  PRIMARY KEY (`id`),
  INDEX `fk_subs_readers_category_category1_idx` (`category_id` ASC),
  INDEX `fk_subs_readers_category_readers1_idx` (`readers_id` ASC),
  CONSTRAINT `fk_subs_readers_category_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subs_readers_category_readers1`
    FOREIGN KEY (`readers_id`)
    REFERENCES `mydb`.`readers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Подписки читателей на категории';


-- -----------------------------------------------------
-- Table `mydb`.`subs_readers_author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subs_readers_author` (
  `id` INT NULL AUTO_INCREMENT COMMENT 'генератор',
  `authors_id` INT NOT NULL COMMENT 'код автора',
  `readers_id` INT NOT NULL COMMENT 'код читателя',
  `created_id` DATETIME NULL COMMENT 'дата создания',
  `modified_id` DATETIME NULL COMMENT 'дата модификации',
  PRIMARY KEY (`id`),
  INDEX `fk_Subs_readers_author_authors1_idx` (`authors_id` ASC),
  INDEX `fk_Subs_readers_author_readers1_idx` (`readers_id` ASC),
  CONSTRAINT `fk_Subs_readers_author_authors1`
    FOREIGN KEY (`authors_id`)
    REFERENCES `mydb`.`authors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Subs_readers_author_readers1`
    FOREIGN KEY (`readers_id`)
    REFERENCES `mydb`.`readers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Подписки читателей на авторов';


-- -----------------------------------------------------
-- Table `mydb`.`books_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`books_category` (
  `id` INT NULL AUTO_INCREMENT COMMENT 'генератор',
  `books_id` INT NULL COMMENT 'код книги',
  `category_id` INT NULL COMMENT 'код категории',
  `created_id` DATETIME NULL COMMENT 'дата создания',
  `modified_id` DATETIME NULL COMMENT 'дата модификации',
  INDEX `fk_Books_has_Category_Category1_idx` (`category_id` ASC),
  INDEX `fk_Books_has_Category_Books1_idx` (`books_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Books_has_Category_Books1`
    FOREIGN KEY (`books_id`)
    REFERENCES `mydb`.`books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Books_has_Category_Category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Связь книг с категориями';


-- -----------------------------------------------------
-- Table `mydb`.`books_authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`books_authors` (
  `id` INT NULL AUTO_INCREMENT COMMENT 'генератор',
  `books_id` INT NULL COMMENT 'код книги',
  `authors_id` INT NULL COMMENT 'код автора',
  `created_id` DATETIME NULL COMMENT 'дата создания',
  `modified_id` DATETIME NULL COMMENT 'дата модификации',
  INDEX `fk_Books_has_Authors_Authors1_idx` (`authors_id` ASC),
  INDEX `fk_Books_has_Authors_Books1_idx` (`books_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Books_has_Authors_Books1`
    FOREIGN KEY (`books_id`)
    REFERENCES `mydb`.`books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Books_has_Authors_Authors1`
    FOREIGN KEY (`authors_id`)
    REFERENCES `mydb`.`authors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Связь авторов с книгами';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
